<a href="https://colab.research.google.com/github/lexinejazly-asuncion/Hallucination_Detection/blob/main/Hallucination_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

hall_dec_pd = pd.read_parquet("hf://datasets/PatronusAI/HaluBench/data/test-00000-of-00001.parquet")

In [7]:
hall_dec_pd.head()

,id,passage,question,answer,label,source_ds
0,d3fb4c3c-d21b-480a-baa0-98d6d0d17c1d,Hoping to rebound from the road loss to the Ch...,Which team scored the longest field goal kick ...,"['Rams', 'second', 'Marc Bulger', 'Kevin Curtis']",FAIL,DROP
1,8603663e-c53b-46db-a482-a867f12ff3b4,"As of the census of 2000, there were 218,590 p...",How many percent were not Irish?,87.1,FAIL,DROP
2,c63a73e5-2c91-489b-bd24-af150ddfa82c,Hoping to rebound from the road loss to the Ch...,How many yards was the second longest field go...,42,FAIL,DROP
3,52db14ed-5426-46ec-b0ae-4ef843b2d692,Hoping to rebound from their tough overtime ro...,How long was the last touchdown?,18-yard,FAIL,DROP
4,31b36417-aad1-412c-b0e5-9c1faaed233f,"As of the census of 2000, there were 218,590 p...",How many in percent from the census weren't Ir...,87.1,FAIL,DROP

In [4]:
hall_dec_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14900 entries, 0 to 14899
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         14900 non-null  object
 1   passage    14900 non-null  object
 2   question   14900 non-null  object
 3   answer     14900 non-null  object
 4   label      14900 non-null  object
 5   source_ds  14900 non-null  object
dtypes: object(6)
memory usage: 698.6+ KB

In [5]:
hall_dec_pd.describe()

,id,passage,question,answer,label,source_ds
count,14900,14900,14900,14900,14900,14900
unique,14900,12419,13798,13543,2,6
top,covidqa-1538,Chikungunya: A Potentially Emerging Epidemic?\...,leasing meaning,yes,PASS,halueval
freq,1,67,6,159,7730,10000